rules:
  - label: "type: chore"
    files:
      - "*.yml"
      - "*.conf"
      - "*.sbt"
      - "*.json"
      - "*.xml"
      - "Dockerfile"
    branch:
      - '/chore\/.+/'
      - '/refactor\/.+/'
      - '/maintenance\/.+/'
    title:
      - /chore/i
      - /refactor/i

  - label: "type: fix"
    branch:
      - '/fix\/.+/'
      - '/hotfix\/.+/'
      - '/bugfix\/.+/'
      - '/patch\/.+/'
    title:
      - /fix/i
      - /hotfix/i
      - /bugfix/i
      - /patch/i

  - label: "type: feature"
    branch:
      - '/feat\/.+/'
      - '/feature\/.+/'
      - '/enhancement\/.+/'
      - '/new\/.+/'
    title:
      - /feat/i
      - /feature/i
      - /enhancement/i
      - /new/i

  - label: "type: docs"
    files:
      - "*.md"
      - "*.txt"
      - "*.rst"
      - "*.wiki"
      - "*.html"
    branch:
      - '/doc\/.+/'
      - '/docs\/.+/'
    title:
      - /doc/i
      - /docs/i
