name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking change'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
      - 'perf'
      - 'performance'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: 'maintenance'
    files:
      - '*.yml'
      - '*.conf'
      - '*.sbt'
    branch:
      - '/chore\/.+/'
      - '/refactor\/.+/'
      - '/maintenance\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feat\/.+/'
      - '/refactor\/.+/'
  - label: 'docs'
    files:
      - '*.md'
      - '*.txt'
    branch:
      - '/doc\/.+/'
      - '/docs\/.+/'
