# Use the smallest possible Tailcall image
FROM alpine:latest

# Set tailcall version
ARG TAILCALL_VERSION=v0.13.0

# Install curl
RUN apk add --no-cache curl \
    && curl -sSL https://raw.githubusercontent.com/tailcallhq/tailcall/${TAILCALL_VERSION}/install.sh | bash -s -- ${TAILCALL_VERSION}

# Set the default command to tailcall
CMD ["tc"]
