mod ambiguous_type;
mod consolidate_url;
mod flatten;
mod improve_type_names;
mod merge_types;
mod nested_unions;
mod preset;
mod required;
mod tree_shake;
mod union_input_type;

pub use ambiguous_type::{AmbiguousType, Resolution};
pub use consolidate_url::ConsolidateURL;
use flatten::Flatten;
pub use improve_type_names::ImproveTypeNames;
pub use merge_types::TypeMerger;
pub use nested_unions::NestedUnions;
pub use preset::Preset;
pub use required::Required;
pub use tree_shake::TreeShake;
pub use union_input_type::UnionInputType;
