name: Spell check

on:
  push:
    branches:
      - "**"
    paths:
      - "docs/**"
      - "**.md"
      - "**.rs"
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
    paths:
      - "docs/**"
      - "**.md"
      - "**.rs"

jobs:
  check_spelling:
    name: Check spelling
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          skip: ".git,*/package.json,*/package-lock.json,*.lock,.github,.vscode,assets, *.snap"
          ignore_words_file: .codespellignore
          check_hidden: false
